### PR TITLE
corrected some metadata mismatches

### PR DESCRIPTION
**Pull request by davbre**
Some updates:
- Renamed "rolef" to "role"
- Renamed "category" to "classification"
- Removed "image_rights" as it is not present in the csv files.

### CODE REVIEW

**Comment by workergnome** [comment]
Hi there—thank you for this!   

I think that the changes on your branch got propagated into the pull request. However, most of them are fine by me, too

The only one that's odd to me is the `creation_date_earliest`, `creation_date_latest`, and `acquisition_date` are not dates.  I just checked, and they're all either dates or null.  I realize that they're listed as required, and they're null, and that's a problem, but that's an actual problem with the data, not with the datapackage.json.  (We shouldn't have things in our collection where we don't know when we acquired them!)  

`creation_date` is indeed a string, and artist birth/death dates are tricky, since they can be pipe-separated dates, which don't parse as strings.  (If you've got a clever idea for many-to-many in CSV, please, please let me know!)

Would you mind making a couple changes to your pull request?  

* change those three fields back to 'date'
* pull out the mira specific bits for `provenance_text` and `image_url`

If you'd rather, I can make your changes directly, rather than via this pull request.

Also—could you add your name to the `CONTRIBUTORS` file?

Thanks!

**Comment by davbre** [comment]
@workergnome - yes, I thought when I made the initial pull request it would only relate to the first commit. In any case, I've updated the datapackage.json file as you suggested.

**Comment by workergnome** [comment]
Fantastic!  Thank you so much.

**Comment by davbre** [comment]
You're welcome!

**Pull request merged**
